# Generated by Django 3.0.5 on 2021-07-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20210703_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='doctorName',
            new_name='kin',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='symptons',
            new_name='patientCondition',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='medicalHist',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referralDate',
        ),
        migrations.AddField(
            model_name='referral',
            name='history',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='patientNumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referFrom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referTo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
