# Generated by Django 3.0.5 on 2021-07-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20210718_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
