# Generated by Django 3.0.5 on 2021-07-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_referral_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='mobility',
            field=models.CharField(choices=[('Bed Bound', 'Bed Bound'), ('Wheelchair', 'Wheelchair'), ('Crutches', 'Crutches'), ('Walking Frame', 'Walking Frame'), ('Requires Assistance', 'Requires Assistance'), ('Independent', 'Independent')], default='Bed Bound', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referralReason',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('OutPatient', 'OutPatient'), ('Community', 'Communnity')], default='Inpatient', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='selfCare',
            field=models.CharField(choices=[('Carer Dependent', 'Carer Dependent'), ('Requires Commode', 'Requires Commode'), ('Requires Modified Washroom', 'Requires Modified Washroom'), ('Independent', 'Independent')], default='Carer Dependent', max_length=100, null=True),
        ),
    ]
