# Generated by Django 3.0.5 on 2021-07-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20210719_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
