# Generated by Django 3.0.5 on 2021-07-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_referral_patientid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('referralDate', models.DateField(auto_now=True)),
                ('referralReason', models.TextField(max_length=500)),
                ('primaryDiagnose', models.CharField(max_length=200, null=True)),
                ('treatments', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
